---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato
  template:
    metadata: 
      labels: 
        app: zomato
    spec:
      containers:
        - name: my-cont
          image: nginx
          ports:
            - containerPort: 80
