---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: my-temp
      labels:
        app: tomcat
    spec:
      containers:
        - name: main-cont
          image: tomcat:9
          volumeMounts:
            - name: logs-volume
              mountPath: /usr/local/tomcat/logs

        - name: side-car
          image: docker.elastic.co/beats/filebeat:8.0.0
          volumeMounts:
            - name: logs-volume
              mountPath: /var/log/tomcat
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: pvc-1
